/*
 * Created on 2026-05-25 ( 18:46:57 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.persistence.entities;

import java.io.Serializable;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import java.math.BigDecimal;


/**
 * JPA entity class for "Calificacioncriterio"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "calificacioncriterio")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class CalificacioncriterioEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Integer id ;

    //--- OTHER DATA FIELDS 
    @Column(name="puntuacion")
    private BigDecimal puntuacion ;

    @Column(name="id_aspirante")
    private Integer    idAspirante ;

    @Column(name="id_criteriocohorte")
    private Integer    idCriteriocohorte ;

    //--- LINKS ( RELATIONSHIPS )
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name="id_aspirante", referencedColumnName="id", insertable=false, updatable=false)
    private AspiranteEntity  aspirante ; 

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name="id_criteriocohorte", referencedColumnName="id", insertable=false, updatable=false)
    private CriteriocohorteEntity criteriocohorte ; 

}
