/*
 * Created on 2026-05-18 ( 01:57:49 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.CriterioevaluacionEntity;
import ufps.edu.co.persistence.repositories.CriterioevaluacionRepository;
import ufps.edu.co.rest.dto.CriterioevaluacionDTO;
import ufps.edu.co.rest.services.commons.GenericService;

/**
 * REST service for entity "Criterioevaluacion" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class CriterioevaluacionService extends GenericService<CriterioevaluacionEntity, CriterioevaluacionDTO> {

    @Autowired
    private CriterioevaluacionRepository repository;

    public CriterioevaluacionService() {
        super(CriterioevaluacionEntity.class, CriterioevaluacionDTO.class);
    }

    @Override
    protected CriterioevaluacionDTO entityToDto(CriterioevaluacionEntity e) {
        return CriterioevaluacionDTO.builder()
                .id(e.getId())
                .nombre(e.getNombre())
                .activo(e.getActivo())
                .descripcion(e.getDescripcion())
                .peso(e.getPeso())
                .idprograma(e.getIdPrograma())
                .build();
    }

    @Transactional(readOnly = true)
    public List<CriterioevaluacionDTO> findAll() {
        return entityListToDtoList(repository.findAll());
    }

    @Transactional(readOnly = true)
    public List<CriterioevaluacionDTO> findByIdPrograma(Integer idPrograma) {
        return entityListToDtoList(repository.findByIdPrograma(idPrograma));
    }

    @Transactional(readOnly = true)
    public CriterioevaluacionDTO findById(Integer id) {
        return entityToDto(repository.findById(id));
    }

    @Transactional(readOnly = true)
    public List<CriterioevaluacionDTO> findAllByIds(List<Integer> ids) {
        if (ids == null || ids.isEmpty()) return List.of();
        return entityListToDtoList(repository.findAllById(ids));
    }

    public CriterioevaluacionDTO create(CriterioevaluacionDTO dto) {
        return entityToDto(repository.save(toEntity(dto)));
    }

    public CriterioevaluacionDTO update(Integer id, CriterioevaluacionDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Criterioevaluacion no encontrado con id: " + id));
        dto.setId(id);
        return entityToDto(repository.save(toEntity(dto)));
    }

    public void deleteById(Integer id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Criterioevaluacion no encontrado con id: " + id));
        repository.deleteById(id);
    }

    private CriterioevaluacionEntity toEntity(CriterioevaluacionDTO dto) {
        return CriterioevaluacionEntity.builder()
                .id(dto.getId())
                .nombre(dto.getNombre())
                .activo(dto.getActivo())
                .descripcion(dto.getDescripcion())
                .peso(dto.getPeso())
                .idPrograma(dto.getIdprograma())
                .build();
    }
}
