/*
 * Created on 2026-05-24 ( 17:03:35 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services;

import java.util.List;
import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.DocumentoEntity;
import ufps.edu.co.persistence.repositories.DocumentoRepository;
import ufps.edu.co.rest.dto.DocumentoDTO;
import ufps.edu.co.rest.dto.EstadodocumentoDTO;
import ufps.edu.co.rest.services.commons.GenericService;

/**
 * REST service for entity "Documento" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class DocumentoService extends GenericService<DocumentoEntity, DocumentoDTO> {

    @Autowired
    private DocumentoRepository repository;

    public DocumentoService() {
        super(DocumentoEntity.class, DocumentoDTO.class);
    }

    @Override
    protected DocumentoDTO entityToDto(DocumentoEntity e) {
        EstadodocumentoDTO estadodocumentoDto = e.getEstadodocumento() != null ? EstadodocumentoDTO.builder()
                .id(e.getEstadodocumento().getId())
                .estado(e.getEstadodocumento().getEstado())
                .build() : null;
        return DocumentoDTO.builder()
                .id(e.getId())
                .enlaceurl(e.getEnlaceurl())
                .fechacargue(e.getFechacargue())
                .keyfile(e.getKeyfile())
                .observaciones(e.getObservaciones())
                .idAdministrativo(e.getIdAdministrativo())
                .idAspirante(e.getIdAspirante())
                .idEstadodocumento(e.getIdEstadodocumento())
                .idPlazo(e.getIdPlazo())
                .idDocumentosrequisitoconsejocohorte(e.getIdDocumentosrequisitoconsejocohorte())
                .idDocumentosrequisitoprogramacohorte(e.getIdDocumentosrequisitoprogramacohorte())
                .estadodocumento(estadodocumentoDto)
                .build();
    }

    @Transactional(readOnly = true)
    public List<DocumentoDTO> findAll() {
        return entityListToDtoList(repository.findAll());
    }

    @Transactional(readOnly = true)
    public DocumentoDTO findById(Integer id) {
        return entityToDto(repository.findById(id));
    }

    public DocumentoDTO create(DocumentoDTO dto) {
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public DocumentoDTO update(Integer id, DocumentoDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Documento no encontrado con id: " + id));
        dto.setId(id);
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public void deleteById(Integer id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Documento no encontrado con id: " + id));
        repository.deleteById(id);
    }

    public int updateEstadoDocumentoById(Integer idDocumento, Integer idEstado, String observaciones) {
        return repository.updateEstadoDocumentoById(idDocumento, idEstado, observaciones);
    }

    @Transactional(readOnly = true)
    public List<DocumentoDTO> findByIdAspirante(Integer idAspirante) {
        return entityListToDtoList(repository.findByIdAspirante(idAspirante));
    }

    @Transactional(readOnly = true)
    public List<DocumentoDTO> findByIdAspiranteIn(List<Integer> ids) {
        if (ids == null || ids.isEmpty()) return List.of();
        return entityListToDtoList(repository.findByIdAspiranteIn(ids));
    }

    @Transactional(readOnly = true)
    public Optional<DocumentoDTO> findByIdAspiranteAndIdDocumentosrequisitoconsejocohorte(Integer idAspirante,
            Integer idDocumentosrequisitoconsejocohorte) {
        return repository
                .findByIdAspiranteAndIdDocumentosrequisitoconsejocohorte(idAspirante, idDocumentosrequisitoconsejocohorte)
                .map(this::entityToDto);
    }

    @Transactional(readOnly = true)
    public Optional<DocumentoDTO> findByIdAspiranteAndIdDocumentosrequisitoprogramacohorte(Integer idAspirante,
            Integer idDocumentosrequisitoprogramacohorte) {
        return repository
                .findByIdAspiranteAndIdDocumentosrequisitoprogramacohorte(idAspirante, idDocumentosrequisitoprogramacohorte)
                .map(this::entityToDto);
    }

    @Transactional(readOnly = true)
    public int countByIdDocumentosrequisitoconsejocohorte(Integer idDocumentosrequisitoconsejocohorte) {
        return repository.countByIdDocumentosrequisitoconsejocohorte(idDocumentosrequisitoconsejocohorte);
    }

    @Transactional(readOnly = true)
    public int countByIdDocumentosrequisitoprogramacohorte(Integer idDocumentosrequisitoprogramacohorte) {
        return repository.countByIdDocumentosrequisitoprogramacohorte(idDocumentosrequisitoprogramacohorte);
    }
}
