/*
 * Created on 2026-05-24 ( 17:03:36 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.DocumentopersonaEntity;
import ufps.edu.co.persistence.repositories.DocumentopersonaRepository;
import ufps.edu.co.rest.dto.DocumentopersonaDTO;
import ufps.edu.co.rest.services.commons.GenericService;

/**
 * REST service for entity "Documentopersona" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class DocumentopersonaService extends GenericService<DocumentopersonaEntity, DocumentopersonaDTO> {

    @Autowired
    private DocumentopersonaRepository repository;

    public DocumentopersonaService() {
        super(DocumentopersonaEntity.class, DocumentopersonaDTO.class);
    }

    @Transactional(readOnly = true)
    public List<DocumentopersonaDTO> findAll() {
        return entityListToDtoList(repository.findAll());
    }

    @Transactional(readOnly = true)
    public boolean existsByNumerodocumentoAndIdTipodocumento(String numerodocumento, Integer idTipodocumento) {
        return repository.existsByNumerodocumentoAndIdTipodocumento(numerodocumento, idTipodocumento);
    }

    @Transactional(readOnly = true)
    public DocumentopersonaDTO findById(Integer id) {
        return entityToDto(repository.findById(id));
    }

    public DocumentopersonaDTO create(DocumentopersonaDTO dto) {
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public DocumentopersonaDTO update(Integer id, DocumentopersonaDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Documentopersona no encontrado con id: " + id));
        dto.setId(id);
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public void deleteById(Integer id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Documentopersona no encontrado con id: " + id));
        repository.deleteById(id);
    }
}