/*
 * Created on 2026-05-18 ( 01:57:51 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.*;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.EntrevistaEntity;
import ufps.edu.co.persistence.repositories.EntrevistaRepository;
import ufps.edu.co.persistence.repositories.EstadoRepository;
import ufps.edu.co.rest.dto.EntrevistaDTO;
import ufps.edu.co.rest.dto.EstadoDTO;
import ufps.edu.co.rest.dto.TipoentrevistaDTO;
import ufps.edu.co.rest.dto.UbicacionDTO;
import ufps.edu.co.rest.services.commons.GenericService;

/**
 * REST service for entity "Entrevista" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class EntrevistaService extends GenericService<EntrevistaEntity, EntrevistaDTO> {

    @Autowired
    private EntrevistaRepository repository;

    @Autowired
    private EstadoRepository estadoRepository;

    public EntrevistaService() {
        super(EntrevistaEntity.class, EntrevistaDTO.class);
    }

    @Override
    protected EntrevistaDTO entityToDto(EntrevistaEntity e) {
        EstadoDTO estadoDto = e.getEstado() != null ? EstadoDTO.builder()
                .id(e.getEstado().getId())
                .tipo(e.getEstado().getTipo())
                .entidad(e.getEstado().getEntidad())
                .build() : null;
        TipoentrevistaDTO tipoentrevistaDto = e.getTipoentrevista() != null ? TipoentrevistaDTO.builder()
                .id(e.getTipoentrevista().getId())
                .tipo(e.getTipoentrevista().getTipo())
                .descripcion(e.getTipoentrevista().getDescripcion())
                .build() : null;
        UbicacionDTO ubicacionDto = e.getUbicacion() != null ? UbicacionDTO.builder()
                .id(e.getUbicacion().getId())
                .direccion(e.getUbicacion().getDireccion())
                .build() : null;
        return EntrevistaDTO.builder()
                .id(e.getId())
                .fecha(e.getFecha())
                .tiempo(e.getTiempo())
                .motivocambio(e.getMotivocambio())
                .idAspirante(e.getIdAspirante())
                .idEstado(e.getIdEstado())
                .idTipoentrevista(e.getIdTipoentrevista())
                .idUbicacion(e.getIdUbicacion())
                .estado(estadoDto)
                .tipoentrevista(tipoentrevistaDto)
                .ubicacion(ubicacionDto)
                .build();
    }

    @Transactional(readOnly = true)
    public List<EntrevistaDTO> findAll() {
        return entityListToDtoList(repository.findAll());
    }

    @Transactional(readOnly = true)
    public Page<EntrevistaDTO> findAll(Pageable pageable) {
        return repository.findAll(pageable).map(this::entityToDto);
    }

    @Transactional(readOnly = true)
    public EntrevistaDTO findById(Integer id) {
        return entityToDto(repository.findById(id));
    }

    public EntrevistaDTO create(EntrevistaDTO dto) {
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public EntrevistaDTO update(Integer id, EntrevistaDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Entrevista no encontrado con id: " + id));
        dto.setId(id);
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public void deleteById(Integer id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Entrevista no encontrado con id: " + id));
        repository.deleteById(id);
    }

    @Transactional(readOnly = true)
    public List<EntrevistaDTO> findByIdAspirante(Integer idAspirante) {
        return entityListToDtoList(repository.findByIdAspirante(idAspirante));
    }

    public EntrevistaDTO changeEstado(Integer id, Integer idEstado, String expectedCurrentEstado) {
        EntrevistaEntity entity = repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Entrevista no encontrada con id: " + id));
        String estadoActual = entity.getEstado() != null ? entity.getEstado().getTipo() : "";
        if (!expectedCurrentEstado.equalsIgnoreCase(estadoActual)) {
            throw new RuntimeException(
                    "La entrevista no está en estado '" + expectedCurrentEstado + "'. Estado actual: " + estadoActual);
        }
        entity.setIdEstado(idEstado);
        repository.save(entity);
        return repository.findById(id).map(this::entityToDto)
                .orElseThrow(() -> new RuntimeException("Entrevista no encontrada con id: " + id));
    }

    public EntrevistaDTO changeEstadoWithMotivo(Integer id, Integer idEstado, String expectedCurrentEstado, String motivocambio) {
        EntrevistaEntity entity = repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Entrevista no encontrada con id: " + id));
        String estadoActual = entity.getEstado() != null ? entity.getEstado().getTipo() : "";
        if (!expectedCurrentEstado.equalsIgnoreCase(estadoActual)) {
            throw new RuntimeException(
                    "La entrevista no está en estado '" + expectedCurrentEstado + "'. Estado actual: " + estadoActual);
        }
        entity.setIdEstado(idEstado);
        entity.setMotivocambio(motivocambio);
        repository.save(entity);
        return repository.findById(id).map(this::entityToDto)
                .orElseThrow(() -> new RuntimeException("Entrevista no encontrada con id: " + id));
    }

    public EntrevistaDTO reschedule(Integer id, LocalDate fecha, LocalTime tiempo,
            Integer idTipoentrevista, Integer idUbicacion, String motivocambio) {
        EntrevistaEntity entity = repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Entrevista no encontrada con id: " + id));
        String estadoActual = entity.getEstado() != null ? entity.getEstado().getTipo() : "";
        if (!"SOLICITUD DE CAMBIO".equalsIgnoreCase(estadoActual)) {
            throw new IllegalStateException(
                    "La entrevista no está en estado 'SOLICITUD DE CAMBIO'. Estado actual: " + estadoActual);
        }
        Integer idEstadoPendiente = estadoRepository
                .findByTipoIgnoreCaseAndEntidadIgnoreCase("PENDIENTE DE CONFIRMACION", "entrevista")
                .orElseThrow(() -> new RuntimeException("Estado 'PENDIENTE DE CONFIRMACION' no encontrado para entidad 'entrevista'"))
                .getId();
        entity.setFecha(fecha);
        entity.setTiempo(tiempo);
        entity.setIdTipoentrevista(idTipoentrevista);
        entity.setIdUbicacion(idUbicacion);
        entity.setIdEstado(idEstadoPendiente);
        entity.setMotivocambio(motivocambio);
        repository.save(entity);
        return repository.findById(id).map(this::entityToDto)
                .orElseThrow(() -> new RuntimeException("Entrevista no encontrada con id: " + id));
    }

    public EntrevistaDTO rateInterview(Integer id, BigDecimal calificacion) {
        EntrevistaEntity entity = repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Entrevista no encontrada con id: " + id));
        // TODO: asignar calificacion en la entidad cuando el campo exista
        repository.save(entity);
        return repository.findById(id).map(this::entityToDto)
                .orElseThrow(() -> new RuntimeException("Entrevista no encontrada con id: " + id));
    }

    public EntrevistaDTO edit(Integer id, LocalDate fecha, LocalTime tiempo,
            Integer idTipoentrevista, Integer idUbicacion) {
        EntrevistaEntity entity = repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Entrevista no encontrada con id: " + id));
        entity.setFecha(fecha);
        entity.setTiempo(tiempo);
        entity.setIdTipoentrevista(idTipoentrevista);
        entity.setIdUbicacion(idUbicacion);
        repository.save(entity);
        return repository.findById(id).map(this::entityToDto)
                .orElseThrow(() -> new RuntimeException("Entrevista no encontrada con id: " + id));
    }

    public EntrevistaDTO requestChange(Integer id, String motivocambio) {
        EntrevistaEntity entity = repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Entrevista no encontrada con id: " + id));
        String estadoActual = entity.getEstado() != null ? entity.getEstado().getTipo() : "";
        if (!"PENDIENTE DE CONFIRMACION".equalsIgnoreCase(estadoActual)) {
            throw new RuntimeException(
                    "La entrevista no está en estado 'PENDIENTE DE CONFIRMACION'. Estado actual: " + estadoActual);
        }
        Integer idEstadoSolicitud = estadoRepository
                .findByTipoIgnoreCaseAndEntidadIgnoreCase("SOLICITUD DE CAMBIO", "entrevista")
                .orElseThrow(() -> new RuntimeException(
                        "Estado 'SOLICITUD DE CAMBIO' no encontrado para entidad 'entrevista'"))
                .getId();
        entity.setIdEstado(idEstadoSolicitud);
        entity.setMotivocambio(motivocambio);
        repository.save(entity);
        return repository.findById(id).map(this::entityToDto)
                .orElseThrow(() -> new RuntimeException("Entrevista no encontrada con id: " + id));
    }
}
