/*
 * Created on 2026-05-30 ( 22:06:14 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services;

import java.util.*;

import org.springframework.beans.factory.annotation.*;
import org.springframework.data.domain.*;
import org.springframework.stereotype.*;
import org.springframework.transaction.annotation.*;

import ufps.edu.co.persistence.entities.*;
import ufps.edu.co.persistence.repositories.*;
import ufps.edu.co.rest.dto.*;
import ufps.edu.co.rest.services.commons.*;

/**
 * REST service for entity "Pagorecibomatricula" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class PagorecibomatriculaService extends GenericService<PagorecibomatriculaEntity, PagorecibomatriculaDTO> {

    @Autowired
    private PagorecibomatriculaRepository repository;

    public PagorecibomatriculaService() {
        super(PagorecibomatriculaEntity.class, PagorecibomatriculaDTO.class);
    }

    @Transactional(readOnly = true)
    public List<PagorecibomatriculaDTO> findAll() {
        return entityListToDtoList(repository.findAll());
    }

    @Transactional(readOnly = true)
    public PagorecibomatriculaDTO findById(Integer id) {
        return entityToDto(repository.findById(id));
    }

    @Transactional(readOnly = true)
    public PagorecibomatriculaDTO findCurrentByIdAspirante(Integer idAspirante) {
        var entity = repository
            .findFirstByPago_IdAspiranteAndEstado_TipoIgnoreCaseAndEstado_EntidadIgnoreCaseOrderByIdDesc(
                idAspirante, "EN CURSO", "pagomatricula");
        if (entity == null) {
            return null;
        }
        return entityToDto(entity);
    }

    @Transactional(readOnly = true)
    public boolean existsCurrentByIdAspirante(Integer idAspirante) {
        return repository.existsByPago_IdAspiranteAndEstado_TipoIgnoreCaseAndEstado_EntidadIgnoreCase(idAspirante,
                "EN CURSO", "pagomatricula");
    }

    public PagorecibomatriculaDTO create(PagorecibomatriculaDTO dto) {
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public PagorecibomatriculaDTO update(Integer id, PagorecibomatriculaDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Pagorecibomatricula no encontrado con id: " + id));
        dto.setId(id);
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    @Transactional(readOnly = true)
    public List<PagorecibomatriculaDTO> findByProgramaId(Integer programaId) {
        return entityListToDtoList(repository.findByProgramaIdWithJoins(programaId));
    }

    @Transactional(readOnly = true)
    public List<PagoreciboDirectorProjectionDTO> findDirectorByProgramaId(Integer programaId) {
        return repository.findDirectorByProgramaId(programaId);
    }

    @Transactional(readOnly = true)
    public Page<PagoreciboDirectorProjectionDTO> findDirectorByProgramaId(Integer programaId, Pageable pageable) {
        return repository.findDirectorByProgramaId(programaId, pageable);
    }

    @Transactional(readOnly = true)
    public List<PagoreciboDirectorProjectionDTO> findDirectorByCohorteId(Integer cohorteId) {
        return repository.findDirectorByCohorteId(cohorteId);
    }

    @Transactional(readOnly = true)
    public Page<PagoreciboDirectorProjectionDTO> findDirectorByCohorteId(Integer cohorteId, Pageable pageable) {
        return repository.findDirectorByCohorteId(cohorteId, pageable);
    }

    public void deleteById(Integer id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Pagorecibomatricula no encontrado con id: " + id));
        repository.deleteById(id);
    }

    @Transactional(readOnly = true)
    public PagorecibomatriculaDTO findLastRejectedByIdAspirante(Integer idAspirante) {
        var entity = repository
            .findFirstByPago_IdAspiranteAndEstado_TipoIgnoreCaseAndEstado_EntidadIgnoreCaseOrderByIdDesc(
                idAspirante, "RECHAZADO", "pagomatricula");
        return entityToDto(entity);
    }

    @Transactional(readOnly = true)
    public PagorecibomatriculaDTO findLastByIdAspirante(Integer idAspirante) {
        var entity = repository.findFirstByPago_IdAspiranteOrderByIdDesc(idAspirante).orElse(null);
        return entityToDto(entity);
    }

    @Transactional(readOnly = true)
    public PagorecibomatriculaDTO findByIdPago(Integer idPago) {
        var entity = repository.findFirstByIdPagoOrderByIdDesc(idPago).orElse(null);
        return entityToDto(entity);
    }
}