/*
 * Created on 2026-05-18 ( 01:57:56 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services;

import java.util.List;
import java.util.Optional;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.UsuarioEntity;
import ufps.edu.co.persistence.repositories.UsuarioRepository;
import ufps.edu.co.rest.dto.ClaveDTO;
import ufps.edu.co.rest.dto.PersonaDTO;
import ufps.edu.co.rest.dto.RolDTO;
import ufps.edu.co.rest.dto.UsuarioDTO;
import ufps.edu.co.rest.services.commons.GenericService;

/**
 * REST service for entity "Usuario" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class UsuarioService extends GenericService<UsuarioEntity, UsuarioDTO> {

    @Autowired
    private UsuarioRepository repository;

    public UsuarioService() {
        super(UsuarioEntity.class, UsuarioDTO.class);
    }

    @Override
    protected UsuarioDTO entityToDto(UsuarioEntity e) {
        RolDTO rolDto = e.getRol() != null ? RolDTO.builder()
                .id(e.getRol().getId())
                .nombre(e.getRol().getNombre())
                .build() : null;

        ClaveDTO claveDto = e.getClave() != null ? ClaveDTO.builder()
                .id(e.getClave().getId())
                .valor(e.getClave().getValor())
                .build() : null;

        PersonaDTO personaDto = e.getPersona() != null ? PersonaDTO.builder()
                .id(e.getPersona().getId())
                .nombres(e.getPersona().getNombres())
                .apellidos(e.getPersona().getApellidos())
                .correo(e.getPersona().getCorreo())
                .celular(e.getPersona().getCelular())
                .telefono(e.getPersona().getTelefono())
                .fechanacimiento(e.getPersona().getFechanacimiento())
                .egresadoufps(e.getPersona().getEgresadoufps())
                .empresa(e.getPersona().getEmpresa())
                .experiencialaboral(e.getPersona().getExperiencialaboral())
                .promediopregrado(e.getPersona().getPromediopregrado())
                .titulopregrado(e.getPersona().getTitulopregrado())
                .titulosposgrados(e.getPersona().getTitulosposgrados())
                .idDocumentopersona(e.getPersona().getIdDocumentopersona())
                .idCapacidadexepcional(e.getPersona().getIdCapacidadexepcional())
                .idDiscapacidad(e.getPersona().getIdDiscapacidad())
                .idEstadocivil(e.getPersona().getIdEstadocivil())
                .idGenero(e.getPersona().getIdGenero())
                .idGrupoetnico(e.getPersona().getIdGrupoetnico())
                .idPoblacionindigena(e.getPersona().getIdPoblacionindigena())
                .idUbicacionnacimiento(e.getPersona().getIdUbicacionnacimiento())
                .idUbicaciontrabajo(e.getPersona().getIdUbicaciontrabajo())
                .idUbicacionvivienda(e.getPersona().getIdUbicacionvivienda())
                .build() : null;

        return UsuarioDTO.builder()
                .id(e.getId())
                .idClave(e.getIdClave())
                .idPersona(e.getIdPersona())
                .idRol(e.getIdRol())
                .nombreusuario(e.getNombreusuario())
                .persona(personaDto)
                .rol(rolDto)
                .clave(claveDto)
                .build();
    }

    @Transactional(readOnly = true)
    public List<UsuarioDTO> findAll() {
        return entityListToDtoList(repository.findAll());
    }

    @Transactional(readOnly = true)
    public UsuarioDTO findById(Integer id) {
        return entityToDto(repository.findById(id));
    }

    @Transactional(readOnly = true)
    public Optional<UsuarioDTO> findByIdPersona(Integer idPersona) {
        return repository.findByIdPersona(idPersona).map(this::entityToDto);
    }

    @Transactional(readOnly = true)
    public UsuarioDTO findByNombreusuario(String nombreusuario) {
        return entityToDto(repository.findByNombreusuario(nombreusuario));
    }

    @Transactional(readOnly = true)
    public Integer findIdPersonaByNombreusuario(String nombreusuario) {
        return repository.findIdPersonaByNombreusuario(nombreusuario).orElse(null);
    }

    @Transactional(readOnly = true)
    public Integer findIdPersonaById(Integer id) {
        return repository.findIdPersonaById(id).orElse(null);
    }

    public UsuarioDTO create(UsuarioDTO dto) {
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public UsuarioDTO update(Integer id, UsuarioDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Usuario no encontrado con id: " + id));
        dto.setId(id);
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public void deleteById(Integer id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Usuario no encontrado con id: " + id));
        repository.deleteById(id);
    }
}