/*
 * Created on 2026-05-24 ( 14:48:44 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.3.0
 */
package ufps.edu.co.rest.services;

import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ufps.edu.co.persistence.entities.ValoresglobalesEntity;
import ufps.edu.co.persistence.repositories.ValoresglobalesRepository;
import ufps.edu.co.rest.dto.ValoresglobalesDTO;
import ufps.edu.co.rest.services.commons.GenericService;

/**
 * REST service for entity "Valoresglobales" <br>
 *
 * @author Telosys
 */
@Service
@Transactional
public class ValoresglobalesService extends GenericService<ValoresglobalesEntity, ValoresglobalesDTO> {

    @Autowired
    private ValoresglobalesRepository repository;

    public ValoresglobalesService() {
        super(ValoresglobalesEntity.class, ValoresglobalesDTO.class);
    }

    @Transactional(readOnly = true)
    public List<ValoresglobalesDTO> findAll() {
        return entityListToDtoList(repository.findAll());
    }

    @Transactional(readOnly = true)
    public List<ValoresglobalesDTO> findByClaveStartingWith(String prefix) {
        return entityListToDtoList(repository.findByClaveStartingWith(prefix));
    }

    @Transactional(readOnly = true)
    public ValoresglobalesDTO findById(Integer id) {
        return entityToDto(repository.findById(id));
    }

    public ValoresglobalesDTO create(ValoresglobalesDTO dto) {
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public ValoresglobalesDTO update(Integer id, ValoresglobalesDTO dto) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Valoresglobales no encontrado con id: " + id));
        dto.setId(id);
        return entityToDto(repository.save(dtoToEntity(dto)));
    }

    public void deleteById(Integer id) {
        repository.findById(id)
                .orElseThrow(() -> new RuntimeException("Valoresglobales no encontrado con id: " + id));
        repository.deleteById(id);
    }
}